#!/usr/bin/env python3
"""Generate llms.txt from data/tutorials.yaml.

The tutorials file is the single source: the site renders it at runtime
and this script flattens it into llms.txt so agent sessions can pull the
whole renewal playbook from one URL. Run via `make llms` after editing
data/tutorials.yaml, and commit both files together.
"""

from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent

HEADER = """\
# Echeance

> Credential renewal playbook for the Neorgon fleet. The real steps to
> obtain, renew and revoke each credential, kept in one place because
> expiry is recurrent and memory is not.

Notes for agents:

- The inventory itself (which credentials exist, when each expires) is
  private: it lives in the owner's browser and in a gitignored
  inventory.local.yaml, never in this file or this repo.
- Steps marked as browser OAuth flows need an interactive terminal; hand
  them to a person instead of retrying them headlessly.
- Source of truth: data/tutorials.yaml in this site's repo. This file is
  generated by scripts/build-llms.py (`make llms`); edit the YAML, not this.
- The rendered version of everything below: https://echeance.neorgon.com/#tutorials
"""


def block(title: str, lines: list[str]) -> str:
    return f"{title}:\n" + "\n".join(lines) + "\n\n"


def main() -> None:
    doc = yaml.safe_load((ROOT / "data" / "tutorials.yaml").read_text())
    tutorials = doc.get("tutorials") or []

    parts = [HEADER, "\n"]
    for t in tutorials:
        parts.append(f"## {t['title']} ({t['id']})\n\n")
        meta = " / ".join(x for x in [t.get("service"), t.get("applies_to")] if x)
        if meta:
            parts.append(f"Service: {meta}\n\n")
        if t.get("signals"):
            parts.append(block("Signals", [f"- {s}" for s in t["signals"]]))
        if t.get("steps"):
            parts.append(block("Steps", [f"{i}. {s}" for i, s in enumerate(t["steps"], 1)]))
        if t.get("verify"):
            parts.append(f"Verify: {t['verify']}\n\n")
        if t.get("revoke"):
            parts.append(f"Revoke or rotate: {t['revoke']}\n\n")
        if t.get("insights"):
            parts.append(block("Insights", [f"- {s}" for s in t["insights"]]))
        if t.get("links"):
            parts.append(block("Links", [f"- {l.get('label', l['url'])}: {l['url']}" for l in t["links"]]))

    out = ROOT / "llms.txt"
    out.write_text("".join(parts).rstrip() + "\n")
    print(f"wrote {out.relative_to(ROOT)}: {len(tutorials)} tutorials")


if __name__ == "__main__":
    main()
